# Generated by Django 3.2.12 on 2022-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0008_contestantform_year_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttype',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='contesttype',
            name='is_payable',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
