# Generated by Django 3.2.12 on 2022-06-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0009_auto_20220611_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttype',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contesttype',
            name='is_payable',
            field=models.BooleanField(default=False),
        ),
    ]
